### ISSUE TITLE
Error: No space left on device

### ISSUE THREAD

**Issue by cyberest** [RennBurris/CrAnberry#3]
Using Lenovo Chromebook duet installation halts with the several error message:
"Error: No space left on device"
Expanding disk image size (dd seek=1G > 2G) in the script made it work in my case.

**Comment by RennBurris** [comment]
Noted. Thank you for letting me know! I minimized the image size the best I could to avoid overusing what storage is available, since there's no RW mounting anyways. If you can find a more exact size, please let me know.
